
# Effects on losers

```{r 305_setup, include=FALSE}
if(!require("broom")){install.packages("broom");  library(broom)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
options(kableExtra.latex.load_packages = FALSE) 
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("naniar")){install.packages("naniar");  library(naniar)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}

set.seed(2016)

d <- read_sav("Data/Goodloser-exp3-orig.sav")

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", warning = FALSE, message = FALSE, fig.height = 6)
```

```{r 305_loser}
#Prepare data 

main_01 <- d %>% 
  mutate(rsp_id = as.numeric(responseid),
         rsp_beg = case_when(r13pad1 == 1 ~ "In favour of ban on begging",
                             r13pad1 == 2 ~ "Against ban on begging"),
         rsp_beg_imp = case_when(r13pad2 %in% 1:2 ~ "Important",
                                  r13pad2 %in% 3:5 ~ "Not important"),
         rsp_toll = case_when(r13pad3 == 1 ~ "In favour of road toll increase of diesel cars",
                              r13pad3 == 2 ~ "Against road toll increase of diesel cars"),
         rsp_toll_imp = case_when(r13pad4 %in% 1:2 ~ "Important",
                                  r13pad4 %in% 3:5 ~ "Not important"),
         treat_outcome = case_when(r13pad5_utfall == 1 ~ "The Yes side won the vote",
                                 r13pad5_utfall == 2 ~ "The No side won the vote"),
         treat_outfav = case_when(r13pad5_sak == 1 & r13pad1 == 1 & r13pad5_utfall == 1 ~ "Favorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 2 & r13pad5_utfall == 2 ~ "Favorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 1 & r13pad5_utfall == 2 ~ "Unfavorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 2 & r13pad5_utfall == 1 ~ "Unfavorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 1 & r13pad5_utfall == 1 ~ "Favorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 2 & r13pad5_utfall == 2 ~ "Favorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 1 & r13pad5_utfall == 2 ~ "Unfavorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 2 & r13pad5_utfall == 1 ~ "Unfavorable outcome"),
         treat_issue = case_when(r13pad5_sak == 1 ~ "Ban on begging",
                               r13pad5_sak == 2 ~ "Road toll increase of diesel cars"),
         treat_winningmargin = case_when(r13pad5_vinnermargin == 1 ~ "Not shown",
                                       r13pad5_vinnermargin == 2 ~ "Slight majority",
                                       r13pad5_vinnermargin == 3 ~ "Large majority"),
         treat_winnergloat = case_when(r13pad5_vinner == 1 ~ "Not shown",
                                     r13pad5_vinner == 2 ~ "Winning politician gloats"),
        treat_prime = case_when(r13pad5_avsender == 1 ~ "Not shown",
                               r13pad5_avsender == 2  | r13pad5_avsender == 5 ~ "Lamenting politician",
                               r13pad5_avsender == 3  | r13pad5_avsender == 6 ~ "Specific good loser message",
                               r13pad5_avsender == 4 | r13pad5_avsender == 7 ~ "Generic good loser message"),
         treat_messenger = case_when(r13pad5_avsender %in% 3:4 ~ "Political leader",
                                   r13pad5_avsender %in% 6:7 ~ "Local newspaper"),
        treat_scale = case_when(r13pad6_ran == 1 ~ "Worded",
                          r13pad6_ran == 2 ~ "Numbered"),

         post_fair = case_when(r13pad6a == 1 | r13pad6b == 1 ~ 5,
                          r13pad6a == 2 | r13pad6b == 2 ~ 4,
                          r13pad6a == 3 | r13pad6b == 3 ~ 3,
                          r13pad6a == 4 | r13pad6b == 4 ~ 2,
                          r13pad6a == 5 | r13pad6b == 5 ~ 1),
          post_reasonable = case_when(r13pad7a == 1 | r13pad7b == 1 ~ 5,
                          r13pad7a == 2 | r13pad7b == 2 ~ 4,
                          r13pad7a == 3 | r13pad7b == 3 ~ 3,
                          r13pad7a == 4 | r13pad7b == 4 ~ 2,
                          r13pad7a == 5 | r13pad7b == 5 ~ 1),
          post_accept = case_when(r13pad8a == 1 | r13pad8b == 1 ~ 5,
                          r13pad8a == 2 | r13pad8b == 2 ~ 4,
                          r13pad8a == 3 | r13pad8b == 3 ~ 3,
                          r13pad8a == 4 | r13pad8b == 4 ~ 2,
                          r13pad8a == 5 | r13pad8b == 5 ~ 1)

  ) %>% 

  replace_with_na_all(condition = ~.x == 98 )%>%  #Recode 98 (not asked) as missing
  filter(!is.na(r13pad6_ran)) %>%  #Remove NA's
## We want the value labels in particular order for the tables and figures.
        mutate(treat_winningmargin = lvls_reorder(treat_winningmargin, c(2, 3, 1)), 
               treat_prime = lvls_reorder(treat_prime, c(3, 2, 4, 1)) 
        )
               
    main_01 <- main_01 %>%   
      filter(treat_outfav == "Unfavorable outcome")
    
    main_02 <- main_01 %>% pivot_longer(cols= c(contains('_imp')), names_to = 'variable', values_to = 'importance')
                                        
    main_02 <- main_02 %>% 
      filter(c(treat_issue == "Ban on begging" & variable == "rsp_beg_imp") | treat_issue == "Road toll increase of diesel cars" & variable == "rsp_toll_imp")
            
``` 

Treatment effects on experimental subjects who find the decision outcome to align unfavorably with their own preferences (N = `r main_01 %>% summarise(n())`)

## Fairness perceptions

<!-- > Figure 4 in the manuscript: -->

<!-- ```{r 305_post_fair_fig4} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_fair, treat_prime) -->

<!-- res_main <- res_main %>% -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_prime" ~ "Democratic\nmessage") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error)), -->
<!--     height = 0) + -->
<!--   geom_point() + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .1), 2), -->
<!--     expand = c(0, 0)) + -->
<!--     labs( -->
<!--     x = "Marginal effect, fairness perception of decision", -->
<!--     y = "") + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7))) -->
<!-- fig_amce -->


<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_fair_fig4.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--  here("output", "nocon", "figs", "pdfs", "fig_losers_fair_fig4.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->
<!-- ``` -->

```{r 305_post_fair_loser}

source("Functions/amce.R")

res_main <-  main_01 %>%
  amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale) 
  
res_main <- res_main %>% 
  mutate(
  treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin",
            treatment == "treat_winnergloat" ~ "Winner\ngloats",
            treatment == "treat_prime" ~ "Democratic\nmessage",
            treatment == "treat_messenger" ~ "Messenger",
            treatment == "treat_issue" ~ "Issue",
            treatment == "treat_scale" ~ "Wording of answer scale")
)

#Figure
fig_amce <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
  facet_grid(
    treatment ~ .,
    scales = "free_y",
    space = "free_y") +
  geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error)),
    height = 0) +
  geom_point() +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1, 1),
    breaks = round(seq(-1, 1, .1), 2),
    expand = c(0, 0)) +
    labs(
    x = "Marginal effect, fairness perception of decision",
    y = "",
    title = 'Average Marginal Component Effect -- Study 3',
    subtitle = 'Sample: Respondents who received an unfavorable outcome') +
  theme_bw() +
  theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7)))
fig_amce


ggsave(
  here("output", "nocon", "figs", "pngs", "fig_losers_fair.png"),
  plot = fig_amce,
  width = 6, height = 2.75
)

ggsave(
 here("output", "nocon", "figs", "pdfs", "fig_losers_fair.pdf"),
  plot = fig_amce,
  width = 6, height = 2.75
)

#table
res_main <- res_main %>% 
  select(value, estimate, std_error, statistic, p_value)


kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))

kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-nocon.html"))
```

### Conditional AMCEs
Issue importance
```{r 306_post_fair_losers_intimportance}

source("Functions/amce.R")

res_main <-  main_02 %>%
  amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale, subgroup = 'importance') 
  
res_main <- res_main %>% 
  mutate(
  treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin",
            treatment == "treat_winnergloat" ~ "Winner\ngloats",
            treatment == "treat_prime" ~ "Democratic\nmessage",
            treatment == "treat_messenger" ~ "Messenger",
            treatment == "treat_issue" ~ "Issue",
            treatment == "treat_scale" ~ "Wording of answer scale")
)

#Figure
fig_amce <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
  facet_grid(
    treatment ~ .,
    scales = "free_y",
    space = "free_y") +
  geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error),
        colour = factor(importance)),
    height = 0) +
  geom_point(aes(colour = factor(importance))) +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1, 1),
    breaks = round(seq(-1, 1, .2), 2),
    expand = c(0, 0)) +
    labs(
    x = "Marginal effect, fairness perception of decision",
    y = "",
    title = 'Average Marginal Component Effect -- Study 3',
    subtitle = 'Sample: Respondents who received an unfavorable outcome. Subgroups: Issue importance.') +
  theme_bw() +
  theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7)))
fig_amce


ggsave(
  here("output", "nocon", "figs", "pngs", "fig_losers_fair_importance.png"),
  plot = fig_amce,
  width = 6, height = 2.75
)

ggsave(
 here("output", "nocon", "figs", "pdfs", "fig_losers_fair_importance.pdf"),
  plot = fig_amce,
  width = 6, height = 2.75
)

#table
res_main <- res_main %>% 
  select(value, estimate, std_error, statistic, p_value, importance)


kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value", "Issue importance")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 6, "Winner gloating" = 4, "Good loser message" = 8, "Messenger" = 4, "Issue" = 4, "Wording of answer scale" = 4))

kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value", "Issue importance")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 6, "Winner gloating" = 4, "Good loser message" = 8, "Messenger" = 4, "Issue" = 4, "Wording of answer scale" = 4))%>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-importance-nocon.html"))
```

Issue (ban on begging or road toll)
```{r 305_post_fair_loser_issue}

source("Functions/amce.R")

res_main <-  main_01 %>%
  amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue,treat_scale, subgroup = 'treat_issue') 
  
res_main <- res_main %>% 
  mutate(
  treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin",
            treatment == "treat_winnergloat" ~ "Winner\ngloats",
            treatment == "treat_prime" ~ "Democratic\nmessage",
            treatment == "treat_messenger" ~ "Messenger",
            treatment == "treat_issue" ~ "Issue",
            treatment == "treat_scale" ~ "Wording of answer scale")
)

#Figure
fig_amce <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
  facet_grid(
    treatment ~ .,
    scales = "free_y",
    space = "free_y") +
   geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error),
        colour = factor(treat_issue)),
    height = 0) +
  geom_point(aes(colour = factor(treat_issue))) +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1, 1),
    breaks = round(seq(-1, 1, .2), 2),
    expand = c(0, 0)) +
    labs(
    x = "Marginal effect, fairness perception of decision",
    y = "",
    title = 'Average Marginal Component Effect -- Study 3',
    subtitle = 'Sample: Respondents who received an unfavorable outcome') +
  theme_bw() +
  theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7)))
fig_amce


ggsave(
  here("output", "nocon", "figs", "pngs", "fig_losers_intissue_fair.png"),
  plot = fig_amce,
  width = 6, height = 2.75
)

ggsave(
 here("output", "nocon", "figs", "pdfs", "fig_losers_intissue_fair.pdf"),
  plot = fig_amce,
  width = 6, height = 2.75
)

#table
res_main <- res_main %>% 
  select(value, estimate, std_error, statistic, p_value)


kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))

kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-intissue-nocon.html"))
```

<!-- Messenger -->
<!-- ```{r 305_post_fair_loser_intmessenger} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale, subgroup = 'treat_messenger')  -->

<!-- res_main <- res_main %>%  -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin", -->
<!--             treatment == "treat_winnergloat" ~ "Winner\ngloats", -->
<!--             treatment == "treat_prime" ~ "Democratic\nmessage", -->
<!--             treatment == "treat_messenger" ~ "Messenger", -->
<!--             treatment == "treat_issue" ~ "Issue", -->
<!--             treatment == "treat_scale" ~ "Wording of answer scale") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   facet_grid( -->
<!--     treatment ~ ., -->
<!--     scales = "free_y", -->
<!--     space = "free_y") + -->
<!--    geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error), -->
<!--         colour = factor(treat_messenger)), -->
<!--     height = 0) + -->
<!--   geom_point(aes(colour = factor(treat_messenger))) + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .2), 2), -->
<!--     expand = c(0, 0)) + -->
<!--     labs( -->
<!--     x = "Marginal effect, fairness perception of decision", -->
<!--     y = "", -->
<!--     title = 'Average Marginal Component Effect -- Study 3', -->
<!--     subtitle = 'Sample: Respondents who received an unfavorable outcome') + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7))) -->
<!-- fig_amce -->


<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_intmessenger_fair.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--  here("output", "nocon", "figs", "pdfs", "fig_losers_intmessenger_fair.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- #table -->
<!-- res_main <- res_main %>%  -->
<!--   select(value, estimate, std_error, statistic, p_value) -->


<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2)) -->

<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--   kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>%  -->
<!--   cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-intmessenger-nocon.html")) -->
<!-- ``` -->

<!-- Winner gloats -->
<!-- ```{r 305_post_fair_loser_intwinnergloat} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale, subgroup = 'treat_winnergloat')  -->

<!-- res_main <- res_main %>%  -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin", -->
<!--             treatment == "treat_winnergloat" ~ "Winner\ngloats", -->
<!--             treatment == "treat_prime" ~ "Democratic\nmessage", -->
<!--             treatment == "treat_messenger" ~ "Messenger", -->
<!--             treatment == "treat_issue" ~ "Issue", -->
<!--             treatment == "treat_scale" ~ "Wording of answer scale") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   facet_grid( -->
<!--     treatment ~ ., -->
<!--     scales = "free_y", -->
<!--     space = "free_y") + -->
<!--    geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error), -->
<!--         colour = factor(treat_winnergloat)), -->
<!--     height = 0) + -->
<!--   geom_point(aes(colour = factor(treat_winnergloat))) + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .2), 2), -->
<!--     expand = c(0, 0)) + -->
<!--     labs( -->
<!--     x = "Marginal effect, fairness perception of decision", -->
<!--     y = "", -->
<!--     title = 'Average Marginal Component Effect -- Study 3', -->
<!--     subtitle = 'Sample: Respondents who received an unfavorable outcome') + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7))) -->
<!-- fig_amce -->


<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_intwinnergloat_fair.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--  here("output", "nocon", "figs", "pdfs", "fig_losers_intwinnergloat_fair.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- #table -->
<!-- res_main <- res_main %>%  -->
<!--   select(value, estimate, std_error, statistic, p_value) -->


<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2)) -->

<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--   kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>%  -->
<!--   cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-intwinnergloat-nocon.html")) -->
<!-- ``` -->

<!-- Winning margin -->
<!-- ```{r 305_post_fair_loser_intwinningmargin} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale, subgroup = 'treat_winningmargin')  -->

<!-- res_main <- res_main %>%  -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin", -->
<!--             treatment == "treat_winnergloat" ~ "Winner\ngloats", -->
<!--             treatment == "treat_prime" ~ "Democratic\nmessage", -->
<!--             treatment == "treat_messenger" ~ "Messenger", -->
<!--             treatment == "treat_issue" ~ "Issue", -->
<!--             treatment == "treat_scale" ~ "Wording of answer scale") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   facet_grid( -->
<!--     treatment ~ ., -->
<!--     scales = "free_y", -->
<!--     space = "free_y") + -->
<!--    geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error), -->
<!--         colour = factor(treat_winningmargin)), -->
<!--     height = 0) + -->
<!--   geom_point(aes(colour = factor(treat_winningmargin))) + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .2), 2), -->
<!--     expand = c(0, 0)) + -->
<!--     labs( -->
<!--     x = "Marginal effect, fairness perception of decision", -->
<!--     y = "", -->
<!--     title = 'Average Marginal Component Effect -- Study 3', -->
<!--     subtitle = 'Sample: Respondents who received an unfavorable outcome') + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7))) -->
<!-- fig_amce -->


<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_intwinningmargin_fair.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--  here("output", "nocon", "figs", "pdfs", "fig_losers_intwinningmargin_fair.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- #table -->
<!-- res_main <- res_main %>%  -->
<!--   select(value, estimate, std_error, statistic, p_value) -->


<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2)) -->

<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--   kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>%  -->
<!--   cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-intwinningmargin-nocon.html")) -->
<!-- ``` -->

<!-- Wording of scale -->
<!-- ```{r 305_post_fair_loser_intscale} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_fair, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale, subgroup = 'treat_scale')  -->

<!-- res_main <- res_main %>%  -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin", -->
<!--             treatment == "treat_winnergloat" ~ "Winner\ngloats", -->
<!--             treatment == "treat_prime" ~ "Democratic\nmessage", -->
<!--             treatment == "treat_messenger" ~ "Messenger", -->
<!--             treatment == "treat_issue" ~ "Issue", -->
<!--             treatment == "treat_scale" ~ "Wording of answer scale") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   facet_grid( -->
<!--     treatment ~ ., -->
<!--     scales = "free_y", -->
<!--     space = "free_y") + -->
<!--    geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error), -->
<!--         colour = factor(treat_scale)), -->
<!--     height = 0) + -->
<!--   geom_point(aes(colour = factor(treat_scale))) + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .2), 2), -->
<!--     expand = c(0, 0)) + -->
<!--     labs( -->
<!--     x = "Marginal effect, fairness perception of decision", -->
<!--     y = "", -->
<!--     title = 'Average Marginal Component Effect -- Study 3', -->
<!--     subtitle = 'Sample: Respondents who received an unfavorable outcome') + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7))) -->
<!-- fig_amce -->


<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_intscale_fair.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--  here("output", "nocon", "figs", "pdfs", "fig_losers_intscale_fair.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- #table -->
<!-- res_main <- res_main %>%  -->
<!--   select(value, estimate, std_error, statistic, p_value) -->


<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2)) -->

<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effect -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%  -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--   kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>%  -->
<!--   cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-fairness-intscale-nocon.html")) -->
<!-- ``` -->

<!-- ## Reasonable -->
<!-- ```{r 305_post_reasonable_loser} -->

<!-- source("Functions/amce.R") -->

<!-- res_main <-  main_01 %>% -->
<!--   amce(post_reasonable, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale)  -->

<!-- res_main <- res_main %>%  -->
<!--   mutate( -->
<!--   treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin", -->
<!--             treatment == "treat_winnergloat" ~ "Winner\ngloats", -->
<!--             treatment == "treat_prime" ~ "Democratic\nmessage", -->
<!--             treatment == "treat_messenger" ~ "Messenger", -->
<!--             treatment == "treat_issue" ~ "Issue", -->
<!--             treatment == "treat_scale" ~ "Wording of answer scale") -->
<!-- ) -->

<!-- #Figure -->
<!-- fig_amce <- -->
<!--   res_main %>% -->
<!--   ggplot(aes(x = estimate, y = value)) + -->
<!--   facet_grid( -->
<!--     treatment ~ ., -->
<!--     scales = "free_y", -->
<!--     space = "free_y") + -->
<!--   geom_errorbarh( -->
<!--     aes(xmin = estimate - (2 * std_error), -->
<!--         xmax = estimate + (2 * std_error)), -->
<!--     height = 0) + -->
<!--   geom_point() + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   scale_x_continuous( -->
<!--     limits = c(-1, 1), -->
<!--     breaks = round(seq(-1, 1, .2), 2), -->
<!--     expand = c(0, 0)) + -->
<!--    labs( -->
<!--     x = "Marginal effect, reasonable decision", -->
<!--     y = "", -->
<!--     title = 'Average Marginal Component Effects, Study 3',  -->
<!--     subtitle = 'Sample: Respondents who received an unfavorable outcome') + -->
<!--   theme_bw() + -->
<!--   theme(plot.margin = unit(c(2, 2, 2, 2), "mm"), plot.title= element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0),         axis.text.x=element_text(size=rel(0.7))) + -->
<!--   theme(panel.spacing = unit(0.5, "lines")) -->
<!-- fig_amce -->

<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pngs", "fig_losers_reasonable.png"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- ggsave( -->
<!--   here("output", "nocon", "figs", "pdfs", "fig_losers_reasonable.pdf"), -->
<!--   plot = fig_amce, -->
<!--   width = 6, height = 2.75 -->
<!-- ) -->

<!-- #Table -->
<!-- res_main <- res_main %>%  -->
<!--   select(value, estimate, std_error, statistic, p_value) -->

<!-- kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effects", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2)) -->

<!--   kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effects", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>% -->
<!--   kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%  -->
<!--  kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))%>%  -->
<!--   cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-reasonable-nocon.html")) -->

<!-- ``` -->

## Willingnes to accept
```{r 305_post_accept_loser}

source("Functions/amce.R")

res_main <-  main_01 %>%
  amce(post_accept, treat_winningmargin, treat_winnergloat, treat_prime, treat_messenger, treat_issue, treat_scale) 
  
res_main <- res_main %>% 
  mutate(
  treatment =  case_when(treatment == "treat_winningmargin" ~ "Winning\nmargin",
            treatment == "treat_winnergloat" ~ "Winner\ngloats",
            treatment == "treat_prime" ~ "Democratic\nmessage",
            treatment == "treat_messenger" ~ "Messenger",
            treatment == "treat_issue" ~ "Issue",
            treatment == "treat_scale" ~ "Wording of answer scale")
)

#Figure
fig_amce <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
  facet_grid(
    treatment ~ .,
    scales = "free_y",
    space = "free_y") +
  geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error)),
    height = 0) +
  geom_point() +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1, 1),
    breaks = round(seq(-1, 1, .2), 2),
    expand = c(0, 0)) +
   labs(
    x = "Marginal effect, willingnes to accept decision",
    y = "",
    title = 'Average Marginal Component Effect -- Study 3',
    subtitle = 'Sample: Respondents who received an unfavorable outcome') +
  theme_bw() +
  theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),  plot.title = element_text(size=9), plot.subtitle = element_text(size=8), strip.text.y = element_text(size=6, angle=0) ,      axis.text.x=element_text(size=rel(0.7)))
fig_amce

ggsave(
  here("output", "nocon", "figs", "pngs", "fig_losers_accept.png"),
  plot = fig_amce,
  width = 6, height = 2.75
)

ggsave(
  here("output", "nocon", "figs", "pdfs", "fig_losers_accept.pdf"),
  plot = fig_amce,
  width = 6, height = 2.75
)

#table
res_main <- res_main %>% 
  select(value, estimate, std_error, statistic, p_value)


kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effects -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "Issue" = 2, "Wording of answer scale" = 2))

kable(res_main, booktabs = TRUE, caption = "Average Marginal Component Effects -- Study 3", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
 kableExtra::group_rows(index = c("Winning margin" = 3, "Winner gloating" = 2, "Good loser message" = 4, "Messenger" = 2, "issue" = 2, "Wording of answer scale" = 2))%>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-losers-accept-nocon.html"))

```
