# Outcome favorability effect across the three experiments


```{r 401_setup, include=FALSE}
if(!require("broom")){install.packages("broom");  library(broom)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
options(kableExtra.latex.load_packages = FALSE) 
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("naniar")){install.packages("naniar");  library(naniar)}
if(!require("Stack")){install.packages("Stack");  library(Stack)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
# The analysis uses custom functions included in the compendium. Install the included pkg with `devtools::install()` or just install from github with:
#if (!require(wiggle)) {  devtools::install_github("mikajoh/wiggle")}

set.seed(2016)

d1 <- read_sav("Data/Goodloser-exp1.sav")
d2 <- read_sav("Data/Goodloser-exp2.sav")
d3 <- read_sav("Data/Goodloser-exp3-orig.sav")


knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", warning = FALSE, message = FALSE)
```

```{r 402_prepare}
d1 <- d1 %>%  mutate(treatment = lvls_reorder(treatment, c(3, 2, 1)))
d2 <- d2 %>%
  mutate(treatment = lvls_reorder(treatment, c(3, 2, 1, 4, 5)) 
  )


main_03 <- d3 %>% 
  mutate(rsp_id = as.numeric(responseid),
         rsp_beg = case_when(r13pad1 == 1 ~ "In favour of ban on begging",
                             r13pad1 == 2 ~ "Against ban on begging"),
         rsp_beg_imp = case_when(r13pad2 %in% 1:2 ~ "Important",
                                  r13pad2 %in% 3:5 ~ "Not important"),
         rsp_toll = case_when(r13pad3 == 1 ~ "In favour of road toll increase of diesel cars",
                              r13pad3 == 2 ~ "Against road toll increase of diesel cars"),
         rsp_toll_imp = case_when(r13pad4 %in% 1:2 ~ "Important",
                                  r13pad4 %in% 3:5 ~ "Not important"),
         treat_outcome = case_when(r13pad5_utfall == 1 ~ "The Yes side won the vote",
                                 r13pad5_utfall == 2 ~ "The No side won the vote"),
         treat_outfav = case_when(r13pad5_sak == 1 & r13pad1 == 1 & r13pad5_utfall == 1 ~ "Favorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 2 & r13pad5_utfall == 2 ~ "Favorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 1 & r13pad5_utfall == 2 ~ "Unfavorable outcome",
                                  r13pad5_sak == 1 & r13pad1 == 2 & r13pad5_utfall == 1 ~ "Unfavorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 1 & r13pad5_utfall == 1 ~ "Favorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 2 & r13pad5_utfall == 2 ~ "Favorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 1 & r13pad5_utfall == 2 ~ "Unfavorable outcome",
                                  r13pad5_sak == 2 & r13pad3 == 2 & r13pad5_utfall == 1 ~ "Unfavorable outcome"),
         treat_issue = case_when(r13pad5_sak == 1 ~ "Ban on begging",
                               r13pad5_sak == 2 ~ "Road toll increase of diesel cars"),
         treat_winningmargin = case_when(r13pad5_vinnermargin == 1 ~ "Not shown",
                                       r13pad5_vinnermargin == 2 ~ "Slight majority",
                                       r13pad5_vinnermargin == 3 ~ "Large majority"),
         treat_winnergloat = case_when(r13pad5_vinner == 1 ~ "Not shown",
                                     r13pad5_vinner == 2 ~ "Winning politician gloats"),
        treat_prime = case_when(r13pad5_avsender == 1 ~ "Not shown",
                               r13pad5_avsender == 2  | r13pad5_avsender == 5 ~ "No prime",
                               r13pad5_avsender == 3  | r13pad5_avsender == 6 ~ "Specific prime",
                               r13pad5_avsender == 4 | r13pad5_avsender == 7 ~ "General prime"),
         treat_messenger = case_when(r13pad5_avsender %in% 3:4 ~ "Political leader",
                                   r13pad5_avsender %in% 6:7 ~ "Local newspaper"),
         post_fair = case_when(r13pad6a == 1 | r13pad6b == 1 ~ 5,
                          r13pad6a == 2 | r13pad6b == 2 ~ 4,
                          r13pad6a == 3 | r13pad6b == 3 ~ 3,
                          r13pad6a == 4 | r13pad6b == 4 ~ 2,
                          r13pad6a == 5 | r13pad6b == 5 ~ 1),
          post_reasonable = case_when(r13pad7a == 1 | r13pad7b == 1 ~ 5,
                          r13pad7a == 2 | r13pad7b == 2 ~ 4,
                          r13pad7a == 3 | r13pad7b == 3 ~ 3,
                          r13pad7a == 4 | r13pad7b == 4 ~ 2,
                          r13pad7a == 5 | r13pad7b == 5 ~ 1),
          post_accept = case_when(r13pad8a == 1 | r13pad8b == 1 ~ 5,
                          r13pad8a == 2 | r13pad8b == 2 ~ 4,
                          r13pad8a == 3 | r13pad8b == 3 ~ 3,
                          r13pad8a == 4 | r13pad8b == 4 ~ 2,
                          r13pad8a == 5 | r13pad8b == 5 ~ 1)

  ) %>% 

  replace_with_na_all(condition = ~.x == 98 )%>%  #Recode 98 (not asked) as missing
  filter(!is.na(r13pad6_ran)) %>%  #Remove NA's
## We want the value labels in particular order for the tables and figures.
        mutate(treat_winningmargin = lvls_reorder(treat_winningmargin, c(2, 3, 1)), 
               treat_prime = lvls_reorder(treat_prime, c(3, 2, 4, 1)) 
        )
``` 

```{r 402_outfav_fair}

res_main_01 <-  lm(fairness ~ favorability, data = d1) 
res_main_01 <- broom::tidy(res_main_01) %>% 
  mutate(value = case_when(term=='favorabilityUnfavorable' ~ 'Unfavorable outcome'),
         treatment = 'Study 1 -- Swedish vignette')%>% 
  rename(std_error = std.error,
         p_value = p.value)

res_main_02 <-  lm(fairness ~ favorability, data = d2) 
res_main_02 <- broom::tidy(res_main_02)%>% 
  mutate(value = case_when(term=='favorabilityUnfavorable' ~ 'Unfavorable outcome'),
         treatment = 'Study 2 -- Norwegian vignette') %>% 
  rename(std_error = std.error,
         p_value = p.value)

source("Functions/amce.R")

res_main_03 <-  main_03 %>%
  amce(post_fair, treat_outfav)  %>% 
  mutate(treatment =  case_when(treatment == "treat_outfav" ~ "Study 3 -- Norwegian conjoint"))

res_main <- Stack(res_main_01, res_main_02)
res_main <- Stack(res_main, res_main_03)

res_main <- res_main %>%
  filter(value=='Unfavorable outcome') %>% 
  select(treatment, estimate, std_error, statistic, value, p_value)

fig <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
  facet_grid(
    treatment ~ .,
    scales = "free_y",
    space = "free_y") +
  geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error)),
    height = 0) +
  geom_point() +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1.2, 1.2),
    breaks = round(seq(-1, 1, .1), 2),
    expand = c(0, 0)) +
   labs(
    x = "Marginal effect, fairness perception",
    y = "",
    title = 'The outcome favorability effect in three experiments') +
  theme_bw() +
  theme(plot.title = element_text(size=11), plot.margin = unit(c(2, 2, 2, 2), "mm"), strip.text.y = element_text(angle = 0, size=6),   axis.text.x=element_text(size=rel(0.6))) +
  theme(panel.spacing = unit(0.5, "lines"))
fig

ggsave(
  here("output", "outfav-fair.png"),
  plot = fig,
  width = 5.5, height = 2.75
)

ggsave(
  here("output", "outfav-fair.pdf"),
  plot = fig,
  width = 5.5, height = 2.75
)

res_main <- res_main %>% select(-value)
#for bookdown
kable(res_main, booktabs = TRUE, caption = "The outcome favorability effect in three experiments", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) 
#save to file
kable(res_main, booktabs = TRUE, caption = "The outcome favorability effect in three experiments", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-outfav-fair.html"))


```

```{r 4044_outfav_issue}
res_main <-  main_03 %>%
  amce(post_fair, treat_outfav, subgroup = 'treat_issue') 

res_main <- res_main %>%
  filter(value=='Unfavorable outcome') %>% 
  select(treatment, estimate, std_error, statistic, value, p_value, treat_issue)

fig <-
  res_main %>%
  ggplot(aes(x = estimate, y = value)) +
    geom_errorbarh(
    aes(xmin = estimate - (2 * std_error),
        xmax = estimate + (2 * std_error),
        colour = factor(treat_issue)),
    height = 0) +
  geom_point(aes(colour = factor(treat_issue))) +
  geom_vline(aes(xintercept = 0), linetype = "dotted") +
  scale_x_continuous(
    limits = c(-1.2, 1.2),
    breaks = round(seq(-1, 1, .1), 2),
    expand = c(0, 0)) +
   labs(
    x = "Marginal effect, fairness perception",
    y = "",
    title = 'The outcome favorability by political issue, Study 3 -- Norwegian conjoint') +
  theme_bw() +
  theme(plot.title = element_text(size=11), plot.margin = unit(c(2, 2, 2, 2), "mm"), strip.text.y = element_text(angle = 0, size=6),   axis.text.x=element_text(size=rel(0.6))) +
  theme(panel.spacing = unit(0.5, "lines"))
fig

ggsave(
  here("output", "outfav-fair-study3-issue.png"),
  plot = fig,
  width = 5.5, height = 2.75
)

ggsave(
  here("output", "outfav-fair-study3-issue.pdf"),
  plot = fig,
  width = 5.5, height = 2.75
)

res_main <- res_main %>% select(-value) %>% 
  mutate(treatment = case_when(treatment=='treat_outfav' ~ 'Unfavorable outcome'))
#for bookdown
kable(res_main, booktabs = TRUE, caption = "The outcome favorability effect in three experiments", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value", "Issue")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) 
#save to file
kable(res_main, booktabs = TRUE, caption = "The outcome favorability effect in three experiments", col.names = linebreak(c("Treatment value", "Estimate", "Std. Error", "t-statistic", "p value", "Issue")), digits = 2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>% 
  cat(., file = here("output", "nocon", "tbls", "html",  "tbl-outfav-fair-study3-issue.html"))

```